"""Pre-compress the dashboard page at build time.

The page lives as a readable raw string literal in web_interface.cpp, which
stays the single source of truth. This script gzips it and emits a PROGMEM
byte array that the firmware serves with Content-Encoding: gzip.

Why bother: handleRoot() pushes the page synchronously from loop(), so the
control loop is stalled for the whole transfer. At ~20 KB that is 80-160 ms
over a SoftAP link - five to eleven missed 15 ms control periods, while
angle_calc() keeps integrating as though exactly 15 ms had elapsed. Cutting
the payload ~2.7x cuts that stall by the same factor.

Runs as a PlatformIO pre: script, so the generated header can never drift
from the literal it was made from.
"""
import gzip
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "esp32_cube_enc", "web_interface.cpp")
OUT = os.path.join(ROOT, "esp32_cube_enc", "dashboard_gz.h")


def build():
    src = open(SRC, encoding="utf-8").read()
    m = re.search(r'DASHBOARD_HTML\[\] PROGMEM = R"rawliteral\((.*?)\)rawliteral";',
                  src, re.S)
    if not m:
        raise SystemExit("gzip_dashboard: DASHBOARD_HTML literal not found in " + SRC)
    page = m.group(1).encode("utf-8")

    # mtime=0 so the output is byte-identical for identical input - otherwise
    # every build would dirty the header and force a needless recompile.
    blob = gzip.compress(page, compresslevel=9, mtime=0)

    # Skip rewriting when nothing changed, for the same reason.
    body = ",".join(str(b) for b in blob)
    text = (
        "// GENERATED by tools/gzip_dashboard.py - do not edit.\n"
        "// Source: the DASHBOARD_HTML literal in web_interface.cpp\n"
        "// %d bytes of HTML -> %d bytes gzipped (%.2fx)\n"
        "#pragma once\n"
        "#include <Arduino.h>\n"
        "#define DASHBOARD_GZ_LEN %d\n"
        "const uint8_t DASHBOARD_GZ[] PROGMEM = {%s};\n"
        % (len(page), len(blob), len(page) / float(len(blob)), len(blob), body)
    )
    if os.path.exists(OUT) and open(OUT, encoding="utf-8").read() == text:
        print("gzip_dashboard: unchanged (%d -> %d bytes)" % (len(page), len(blob)))
        return
    open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print("gzip_dashboard: %d -> %d bytes (%.2fx)"
          % (len(page), len(blob), len(page) / float(len(blob))))


build()
